### ISSUE TITLE
FIT Files not processing

### ISSUE THREAD

**Issue by Shiiv84** [LightningBugalugs/Fickle-Frostbite#2]
Hey man ... it looks like FIT files are not processing, thought it would take care of those.

**Comment by LightningBugalugs** [comment]
uploaded FIT file processing ... it doesn't process into database/files, but does show data on screen

**Comment by Shiiv84** [comment]
Nice one man. So FIT files aren't able to be loaded into the database?
Could you take me through this fix later today when you have some time?

**Comment by LightningBugalugs** [comment]
sorry they will be able to be loaded, just need to write that code ... the commit does a display of the data to the command window ... next step is to instead of display it save it to the database ... just need to create some tables and sort it all out (probably in mid-january)

```
On Tuesday, December 29, 2015 6:50 AM, Shiiv84 <notifications@github.com> wrote:
```

 Nice one man. So FIT files aren't able to be loaded into the database?
Could you take me through this fix later today when you have some time?
